name: Check Commit Messages

on:
  push:
    branches:
      - '*'  # Trigger on pushes to any branch
  pull_request:
    branches:
      - '*'  # Trigger on pull requests to any branch

jobs:
  commit-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check commit messages
        run: |
          # Get the last commit message
          commit_message=$(git log -1 --pretty=%B)

          # Check if the commit message matches the regex
          if ! echo "$commit_message" | grep -qE '^\[Main-\d+\] - .+$'; then
            echo "ERROR: Commit message does not match format '[Main-xxxx] - Some message'."
            exit 1
          fi