name: Commit Message Check

on:
  push:
    branches:
      - '*'  # Trigger on pushes to any branch
  pull_request:
    branches:
      - '*'  # Trigger on pull requests to any branch

jobs:
  commit-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up script
        run: |
          commit_message=$(git log -1 --pretty=%B | tr -d '\n')
          echo "Commit message: $commit_message"
          echo "Setting up the commit message check script."
          chmod +x ./test.sh  # Make the script executable

      - name: Run commit message check
        run: |
          ./test.sh           # Execute the script